In [1]:
import numpy as np
import pandas as pd
import missingno as msno
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
# Loading Data
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slop', 'ca', 'thal', 'heartdisease']
clivelandData = pd.read_csv('Dataset/cleveland.csv', names = features)
hungarianData = pd.read_csv('Dataset/hungarian.csv', names = features)
switzerlandData = pd.read_csv('Dataset/switzerland.csv', names = features)

datatemp = [clivelandData, hungarianData, switzerlandData]
data = pd.concat(datatemp)
data

age  sex   cp trestbps   chol  fbs restecg thalach exang oldpeak slop  \
0    63.0  1.0  1.0    145.0  233.0  1.0     2.0   150.0   0.0     2.3  3.0   
1    67.0  1.0  4.0    160.0  286.0  0.0     2.0   108.0   1.0     1.5  2.0   
2    67.0  1.0  4.0    120.0  229.0  0.0     2.0   129.0   1.0     2.6  2.0   
3    37.0  1.0  3.0    130.0  250.0  0.0     0.0   187.0   0.0     3.5  3.0   
4    41.0  0.0  2.0    130.0  204.0  0.0     2.0   172.0   0.0     1.4  1.0   
..    ...  ...  ...      ...    ...  ...     ...     ...   ...     ...  ...   
118  70.0  1.0  4.0      115      0    0       1      92     1       0    2   
119  70.0  1.0  4.0      140      0    1       0     157     1       2    2   
120  72.0  1.0  3.0      160      0    ?       2     114     0     1.6    2   
121  73.0  0.0  3.0      160      0    0       1     121     0       0    1   
122  74.0  1.0  2.0      145      0    ?       1     123     0     1.3    1   

      ca thal  heartdisease  
0    0.0  6.0             0  
1    3.0  3.0             2  
2    2.0  7.0             1  
3    0.0  3.0             0  
4    0.0  3.0             0  
..   ...  ...           ...  
118    ?    7             1  
119    ?    7             3  
120    2    ?             0  
121    ?    3             1  
122    ?    ?             1  

[720 rows x 14 columns]

In [3]:
# Preprocessing Data
data = data.drop(['slop', 'ca', 'thal'], axis=1)
data = data.replace('?', np.nan)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imputedData = imp.fit_transform(data)
imputedData

array([[63. ,  1. ,  1. , ...,  0. ,  2.3,  0. ],
       [67. ,  1. ,  4. , ...,  1. ,  1.5,  2. ],
       [67. ,  1. ,  4. , ...,  1. ,  2.6,  1. ],
       ...,
       [72. ,  1. ,  3. , ...,  0. ,  1.6,  0. ],
       [73. ,  0. ,  3. , ...,  0. ,  0. ,  1. ],
       [74. ,  1. ,  2. , ...,  0. ,  1.3,  1. ]])

In [12]:
# Creating Test and Train Data
X_train, X_test, y_train, y_test = train_test_split(imputedData[:, :-1], imputedData[:, -1], test_size=0.3, random_state=42)
X_train


array([[ 57. ,   1. ,   4. , ...,  92. ,   1. ,   3. ],
       [ 34. ,   1. ,   4. , ..., 154. ,   0. ,   0.2],
       [ 63. ,   1. ,   4. , ..., 149. ,   0. ,   2. ],
       ...,
       [ 61. ,   1. ,   4. , ..., 138. ,   1. ,   1.9],
       [ 53. ,   0. ,   2. , ..., 142. ,   1. ,   2. ],
       [ 57. ,   0. ,   4. , ..., 159. ,   0. ,   0. ]])

In [13]:
X_test

array([[ 39. ,   1. ,   3. , ..., 160. ,   0. ,   0. ],
       [ 67. ,   1. ,   3. , ..., 150. ,   0. ,   0.8],
       [ 60. ,   1. ,   4. , ..., 144. ,   1. ,   1.4],
       ...,
       [ 54. ,   1. ,   4. , ...,  91. ,   1. ,   1. ],
       [ 61. ,   1. ,   4. , ..., 145. ,   0. ,   1. ],
       [ 48. ,   1. ,   4. , ...,  92. ,   1. ,   1.5]])

In [14]:
y_train

array([1., 1., 2., 0., 0., 0., 0., 1., 0., 1., 2., 1., 0., 0., 1., 0., 2.,
       1., 0., 3., 0., 1., 1., 1., 3., 0., 0., 1., 0., 2., 2., 0., 3., 3.,
       0., 0., 0., 0., 1., 3., 1., 0., 4., 0., 0., 0., 0., 1., 0., 1., 0.,
       3., 1., 0., 2., 0., 0., 0., 1., 2., 0., 1., 1., 0., 4., 0., 0., 0.,
       2., 0., 1., 0., 2., 0., 1., 0., 0., 1., 0., 0., 0., 3., 0., 1., 0.,
       1., 0., 3., 0., 0., 1., 2., 0., 0., 0., 4., 1., 1., 1., 0., 0., 0.,
       3., 3., 1., 1., 1., 1., 1., 0., 0., 0., 2., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 3., 0., 3., 0., 0., 3., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 1., 2., 0., 0., 0., 1., 0., 3., 1., 2., 1., 0., 2., 3.,
       3., 3., 0., 0., 2., 0., 0., 1., 3., 1., 1., 0., 2., 0., 1., 0., 0.,
       0., 2., 0., 1., 2., 0., 0., 3., 1., 3., 1., 0., 0., 2., 1., 0., 3.,
       4., 0., 1., 0., 1., 0., 3., 3., 0., 0., 0., 0., 2., 0., 2., 4., 0.,
       0., 0., 1., 0., 0., 0., 2., 1., 1., 1., 1., 0., 0., 1., 2., 3., 1.,
       0., 4., 1., 0., 3.

In [15]:
y_test

array([0., 1., 1., 0., 0., 2., 0., 1., 2., 0., 0., 0., 0., 0., 0., 0., 0.,
       4., 1., 3., 0., 0., 0., 1., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0.,
       1., 2., 3., 1., 1., 1., 3., 0., 0., 1., 0., 1., 0., 1., 2., 0., 1.,
       1., 0., 1., 0., 0., 4., 0., 0., 0., 1., 0., 0., 0., 0., 3., 2., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 3., 3., 1., 0., 1., 2., 2.,
       1., 1., 2., 0., 1., 0., 1., 1., 0., 4., 0., 1., 1., 1., 3., 0., 1.,
       0., 0., 0., 0., 2., 3., 0., 2., 3., 0., 3., 0., 1., 0., 0., 2., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 2.,
       4., 3., 3., 0., 0., 1., 0., 1., 0., 0., 2., 0., 1., 2., 0., 0., 1.,
       4., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 3., 0., 3., 2., 0., 0., 4., 0., 0., 2.,
       0., 0., 0., 0., 0., 0., 3., 0., 1., 0., 0., 2., 0., 1., 0., 0., 1.,
       3., 2., 3., 0., 2., 0., 0., 0., 0., 1., 2., 1.])

In [30]:
# Scale Data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
# Build and Train the Model
classifier = svm.SVC(kernel='rbf')
classifier.fit(X_train, y_train)
preds = classifier.predict(X_test)

In [32]:
preds

array([0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 3., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 3., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 3., 2.,
       1., 1., 3., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 3., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 3., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 3., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 3., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 3., 1.])

In [33]:
# Accuracy of Predictions
accuracy_score(y_test, preds)

0.6527777777777778